log:
  disable_sentry: true

# use the book-svc database
db:
  url: "postgres://book:book@localhost:25432/book?sslmode=disable"

eth_minter:
  eth_signer:
  chain_id: 1
  precision: 18
  expiration: 5m

coingecko:
  host:
  endpoint:

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: generator-svc
  service_port: 80
