log:
  disable_sentry: true

database:
  book-svc:
    url: "postgres://book:book@localhost:25432/book?sslmode=disable"
  generator-svc:
    url: "postgres://book:book@localhost:25432/book?sslmode=disable"

task_processor:
  name: task_processor # Name to be displayed in logs
  cursor: 0 # Default cursor value
  limit: 1 # Number of subtasks to be processed during one run (no more than 10)
  runner: # Period settings
    normal_period: 10s
    min_abnormal_period: 10s
    max_abnormal_period: 10s

eth_minter:
  eth_signer:
  chain_id: 1
  precision: 18
  expiration: 5m

coingecko:
  host:
  endpoint:

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: generator-svc
  service_port: 80

pdf_signature_params:
  api_key: b367178b5ddb3ea2cc9add1c9989b1eec155ffce4160b5b8c9777dbe28b9f3a6 #100 free uses only
  params:
    main_height_indent: 441.2381
    line_width_indent: 79.8757
    paragraph_width_indent: 33.821
    upper_line_height_ident: 7.198
    lower_line_height_Ident: 12.9564

#  +-----------BDS-BOOK--------------+
#  |	|        			   		 |
#  |	|        					 |
#  |	|        					 |
#  |	| MainHeightIndent       	 |
#  |	|        					 |
#  |	|        					 |
#  |	v ---------line----------    |
#  |						|		 |
#  |				UpLHI	|		 |
#  |						|		 |
#  |	_  [signaturesignature]  --->| ParagraphWidhtIndent
#  |	|							 |
#  |	|	LowLHI					 |
#  |	v							 |
#  |	  -----------line------ ->   | LineWidthIndent
#  |								 |
#  |								 |
#  +---------------------------------+
